// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZCxE2Pkd_5JKaFEgrQBwPsy74EUv0gg',
    appId: '1:343106123773:web:19294f15dc3bbec63c8b94',
    messagingSenderId: '343106123773',
    projectId: 'restaurants-vendor-app',
    authDomain: 'restaurants-vendor-app.firebaseapp.com',
    databaseURL: 'https://restaurants-vendor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restaurants-vendor-app.appspot.com',
    measurementId: 'G-QHJNPMB55K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCviKf9CBwvjF5pjKsTVzVFiCbvyRfyTVU',
    appId: '1:343106123773:android:774726fb7ea88c343c8b94',
    messagingSenderId: '343106123773',
    projectId: 'restaurants-vendor-app',
    databaseURL: 'https://restaurants-vendor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restaurants-vendor-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLq7j4vPZvIHTP4GbNF-sJ6Qmu_AamCnw',
    appId: '1:343106123773:ios:b6a186e71b12fe243c8b94',
    messagingSenderId: '343106123773',
    projectId: 'restaurants-vendor-app',
    databaseURL: 'https://restaurants-vendor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restaurants-vendor-app.appspot.com',
    iosClientId: '343106123773-ciju0d0u693h0sne3atkcslgbjfuat54.apps.googleusercontent.com',
    iosBundleId: 'com.metascifor.restaurantVendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLq7j4vPZvIHTP4GbNF-sJ6Qmu_AamCnw',
    appId: '1:343106123773:ios:d777cdf8c2332a3b3c8b94',
    messagingSenderId: '343106123773',
    projectId: 'restaurants-vendor-app',
    databaseURL: 'https://restaurants-vendor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restaurants-vendor-app.appspot.com',
    iosClientId: '343106123773-nb2rb9tom6fokkkhq5lv4dvml2jc6g1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.restuarantPagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ZCxE2Pkd_5JKaFEgrQBwPsy74EUv0gg',
    appId: '1:343106123773:web:ce92e14521e4d91a3c8b94',
    messagingSenderId: '343106123773',
    projectId: 'restaurants-vendor-app',
    authDomain: 'restaurants-vendor-app.firebaseapp.com',
    databaseURL: 'https://restaurants-vendor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restaurants-vendor-app.appspot.com',
    measurementId: 'G-2179SRNZ92',
  );
}
