// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUrI2q5lp6rA_UFCBjJ5kyLtSZQWioo4',
    appId: '1:742342151590:web:5f4a25bf1388dd7208d367',
    messagingSenderId: '742342151590',
    projectId: 'resturantpager-bf7bb',
    authDomain: 'resturantpager-bf7bb.firebaseapp.com',
    storageBucket: 'resturantpager-bf7bb.appspot.com',
    measurementId: 'G-TN8WP6Z90X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4spP-xulXjmC98z-eS5ULYJxkf-m5QYU',
    appId: '1:742342151590:android:83ce8a8148ca7dab08d367',
    messagingSenderId: '742342151590',
    projectId: 'resturantpager-bf7bb',
    storageBucket: 'resturantpager-bf7bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKmahV05HwJLixsrR4Nq11dwicHiyxEY',
    appId: '1:742342151590:ios:2f78e0588af1242a08d367',
    messagingSenderId: '742342151590',
    projectId: 'resturantpager-bf7bb',
    storageBucket: 'resturantpager-bf7bb.appspot.com',
    iosBundleId: 'com.example.restuarantPagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOKmahV05HwJLixsrR4Nq11dwicHiyxEY',
    appId: '1:742342151590:ios:2f78e0588af1242a08d367',
    messagingSenderId: '742342151590',
    projectId: 'resturantpager-bf7bb',
    storageBucket: 'resturantpager-bf7bb.appspot.com',
    iosBundleId: 'com.example.restuarantPagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCUrI2q5lp6rA_UFCBjJ5kyLtSZQWioo4',
    appId: '1:742342151590:web:7df497b1fe50023f08d367',
    messagingSenderId: '742342151590',
    projectId: 'resturantpager-bf7bb',
    authDomain: 'resturantpager-bf7bb.firebaseapp.com',
    storageBucket: 'resturantpager-bf7bb.appspot.com',
    measurementId: 'G-SH5QXH55LK',
  );
}
